hometask-1
machikhin-ka/smart-home-2020 pull request #1
Opened 2020-09-30 12:14 UTC by machikhin-ka

2020-10-05 14:16 UTC, a-ivanov requested changes

2020-10-05 14:16 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        SmartHome smartHome = deserialization.deserialize();
Лучше создавать дом внутри метода с общей логикой приложения. Конструктор - просто присваивает аргументы к полям класса.

2020-10-05 14:16 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SensorEventProcessingCycle.java
> +			if (event.getType() == LIGHT_ON || event.getType() == LIGHT_OFF) {
Нарушение OCP, добавление новых событий требует изменения текущего кода. Перенесите логику выбора обработчика в имплементацию обработчика.

2020-10-05 14:16 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/LightHandler.java
> +public class LightHandler {
Чтобы отделить логику обарботчиков от цикла SensorEventProcessingCycle, добавьте интерфейс для обработчиков. Используйте коллекцию объектов этого интерфейсас в SensorEventProcessingCycle.

2020-10-05 14:16 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SensorEventHandler.java
> +	void handle();
Чтобы клиент не знал о конкретном классе-реализации этого интерйейса, перенесите дом и событие в аргументы и вызывайте их в классе с циклом.

2020-10-05 14:16 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SensorEventGetter.java
> +	public SensorEvent getNextSensorEvent() {
Можно выделить интерейс для генерации событий. Так будет легче заменить его на "реальный", читающий настоящие показатели сенсоров.

2020-10-06 18:57 UTC, a-ivanov requested changes

2020-10-06 18:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        RandomSensorEventGetter randomSensorEventGetter = new RandomSensorEventGetter();
Лучше тогда создавать ссылку на интерфейс SensorEventGetter randomSensorEventGetter = new RandomSensorEventGetter();

2020-10-06 18:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        handlers.add(new DoorEventHandler());
см. https://docs.oracle.com/javase/7/docs/api/java/util/Arrays.html#asList(T...)

2020-10-06 18:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorEventHandler.java
> +		if (room.getName().equals("hall")) {
https://github.com/iagoshkov/smart-home-2020/blob/master/STUDENT_GUIDE.md#%D1%80%D0%B0%D0%B7%D0%B4%D0%B5%D0%BB%D1%8F%D0%B9%D1%82%D0%B5-%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%BE%D0%B2-%D0%B8-%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B8-%D1%83%D0%BC%D0%BD%D0%BE%D0%B3%D0%BE-%D0%B4%D0%BE%D0%BC%D0%B0

2020-10-06 18:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorEventHandler.java
> +				new CommandSender().sendCommand(command);
Передавайте CommandSender через конструктор.

2020-10-06 18:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorEventHandler.java
> +				new CommandSender().sendCommand(command);
https://github.com/iagoshkov/smart-home-2020/blob/master/STUDENT_GUIDE.md#%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D0%B0%D0%B2%D0%B0%D0%B9%D1%82%D0%B5-%D0%B7%D0%B0%D0%B2%D0%B8%D1%81%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D0%B8-%D1%81%D0%BD%D0%B0%D1%80%D1%83%D0%B6%D0%B8

2020-10-06 18:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/RandomSensorEventGetter.java
> +public class RandomSensorEventGetter implements  SensorEventGetter {
Getter в Java имеет значение метода в классе по получению данных (типа Light getLight()).
Лучше название заменить на Provider, например.

2020-10-07 09:35 UTC, koctyandr commented on src/main/java/ru/sbt/mipt/oop/DoorEventHandler.java
> +		if (room.getName().equals("hall")) {
исправил в hometask-2

2020-10-12 21:58 UTC, a-ivanov approved these changes

2020-10-17 13:10 UTC, merged